import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Inter, Roboto } from "next/font/google";
import "@/app/main.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Inter as FontSans } from "next/font/google";

export const metadata = {
	title: "Articles - Next.js",
	description: "Generated by Taha",
};

const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export default async function LocaleLayout({ children, params: { locale } }: { children: React.ReactNode; params: { locale: string } }) {
	const messages = await getMessages();

	return (
		<html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"} suppressHydrationWarning>
			<body className={(locale === "ar" ? inter.className : roboto.className, "min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
				<NextIntlClientProvider messages={messages}>
					<main>
						<Header />
						{children}
					</main>
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
