import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Marhey, Roboto, Noto_Sans_Arabic } from "next/font/google";
import "@/app/main.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Metadata } from "next";

export const metadata: Metadata = {
	title: "Articles - Next.js",
	description: "Generated by Taha",
};

const marhey = Marhey({ subsets: ["arabic"], weight: "400" });
const noto = Noto_Sans_Arabic({ subsets: ["arabic"], weight: "500" });
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export default async function LocaleLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const messages = await getMessages();
	const locale = await getLocale();

	return (
		<html
			lang={locale}
			dir={locale === "ar" ? "rtl" : "ltr"}
			suppressHydrationWarning
		>
			<body
				className={`${
					locale === "ar" ? noto.className : roboto.className
				} min-h-screen bg-background antialiased`}
			>
				<NextIntlClientProvider messages={messages}>
					<main>
						<Header />
						{children}
					</main>
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
