import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Inter, Roboto } from "next/font/google";
import "./main.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata = {
	title: "Articles - Next.js",
	description: "Generated by Taha",
};

const inter = Inter({ subsets: ["latin"] });
const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export default async function LocaleLayout({ children, params: { locale } }: { children: React.ReactNode; params: { locale: string } }) {
	const messages = await getMessages();

	return (
		<html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
			<body className={locale === "ar" ? inter.className : roboto.className}>
				<NextIntlClientProvider messages={messages}>
					<main>
						<Header />
						{children}
					</main>
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	);
}
